<!-- This scirpt gets the schedule from the softball league, transforms it how
we want it and gives a nicely formatted HTML table -->

```{r get and generate the table, include = FALSE} 
#in this chunk we generate the table. we set include = FALSE so that this whole
#chunk doesn't show in the output

#we load all necessary packages if you haven't them installed on your system,
#use install.packages("<packagename>") before these lines

library(httr) # is used to get the HTML document
library(xml2) # read out the HTML document
library(rvest) # get individual nodes from the HTML document
library(data.table) #great tool for data wrangling
library(dplyr) #another great tool for data wrangling
library(mgsub) #a speical gsub package to replace multiple strings at once
library(kableExtra) #styling package for kable (to make our nicely formatted table)

#we get the HTML file from the server
abbqs <- GET("http://www.abbqs.at/abbqs-east-2018/")

#we transform it into a more accessible fashion
abbqs <- read_html(abbqs)

#we get the HTML nodes that are named table and select the second table. this
#is where the schedule is
schedule <- html_nodes(abbqs, "table")[2]

#we use html_table to transform it into a more table like object
schedule <- html_table(schedule)

#rbindlist comes with the data.table package. it transforms our list object into a
#data.table (note: a data.table is always also a data.frame)
schedule <- rbindlist(schedule)

#since I play baseball and softball in Austria and I ran into some trouble with
#german Umlaute, I rename the column names here
setnames(schedule, c("Datum", "Heim", "Zeit/Ergebnisse", "Auswaerts", "Austragungsort"))

#my team is the Crazy Geese. So I select all lines with our team in it
schedule <- schedule[Heim == "Crazy Geese Rohrbach" | Auswaerts == "Crazy Geese Rohrbach"]


#i transfer the date column into a date format. (note: you will get a warning message
#that the type was changed to POSIXct. This is fine and actually what we want)
schedule[, Date := strptime(Datum, format = '%Y-%m-%d %H:%M:%S')]

#i want two columns. one with the day of the game and one with the starting time
#here I can read out just the day with the format function and store it in a new
#column named "Datum" (german for Date)
schedule$Datum <- format(schedule$Date, "%d.%m.%Y")

#i do the same thing as with the day here with the starting time. 
schedule[, Beginn := strptime(Date, format = '%Y-%m-%d %H:%M:%S')]
schedule$Beginn <- format(schedule$Beginn, "%H:%M")

#with select from the dplyr package I select and rename the columns in the
#way I want them to be
schedule <- as.data.table(schedule %>%
  select(Datum, Beginn, Gast = Auswaerts, Heim, Austragungsort, Ergebnis_Zeit = `Zeit/Ergebnisse`))
#(Note: I'm not sure about this but I think that select() transfers the data.table into something else
#even though class() still gives me data.table back, just to be sure I wrap the whole comannd into 
#an as.data.table())

#in the "Ergebnis_zeit" column there is either the result of the game or, if the games wasn't
#played yet, the time of the game. I don't want this. I want one column for the date, one for
#the time of the game and one with the result. This is why here I store the line numbers of
#where there is a result in a vector
ergebnisse <- grep(" - ", schedule$Ergebnis_Zeit)
#now I use this vector to fill in the result in the new column "Ergebnis". All the others
#get a " - " because there is no result for future games of course
schedule[ergebnisse, Ergebnis := Ergebnis_Zeit]
schedule[!ergebnisse, Ergebnis := " - "]

#now I create the final table. again with select
schedule <- as.data.table(select(schedule, Datum, Beginn, Gast, Heim, Spielort = Austragungsort, Ergebnis))


#this looks more complicated than it is. mgsub() enables us to replace more than one character string
#at once. so we feed it two vectors. the first one contains what we want to replace and the second one
#with what we want to replace it. It goes in order so for example "Ducksfield Wr.Neustadt" gets 
#replaced with "Wr. Neustadt". Finally we use lapply() to perform this on the whole data.table
schedule <- as.data.table(lapply(schedule, function(x) {
  mgsub(x, c("Ducksfield Wr.Neustadt", "Baseballfeld Rohrbach", "Cubsfield Stockerau",
             "ASKÖ Baseballplatz Wien", "Baseballplatz Freudenau"), c("Wr. Neustadt", "Rohrbach", "Stockerau",
                                                                      "Spenadlwiese - Wien", "Freudenau - Wien"))
}))

#just to make it not too much code at once I here replace the team names and above we were replacing
#the baseball fields
schedule <- as.data.table(lapply(schedule, function(x) {
  mgsub(x, c("Crazy Geese Rohrbach", "Rubberducks Wiener Neustadt", "Wet Sox-Wanderers Wien"), 
        c("Geese Rohrbach", "Rubberducks Wr.N.", "Wet Sox Wien"))
}))

#in the final table I want every game which is played at our home field to be in blue
#therefore I save the lines where this is the case in a variable
blue_rows <- which(schedule$Spielort %in% "Rohrbach")

#we produce our final nicely formatted (HTML) table. I want all the columns to be centered.
#This is what happens in the align argument of the kable function. After that I ensure
#that the table is responsive and with the row_spec function I color in all games that are
#player on our home field
schedule_format <- kable(schedule, align = c("c","c", "c","c","c", "c")) %>%
  kable_styling(bootstrap_options = c("responsive")) %>%
  row_spec(blue_rows, color = "#01023C") 

```
<!-- Now to the part that we actually show the HTML output. I just want a simple line
that says Regular Season and show ther table after it. -->

**Regular Season** 

```{r show the table  , echo = FALSE}
schedule_format
```

<!-- All done. Now we can call this RMD file from the post_to_wordpress.R file with the 
knit2wp function and this part of the website will magically be updated -->
